config/routes.rb
Jlz::Application.routes.draw do
  resources :categories
  resources :picture
  resources :home
  resources :info

  match 'uploader' => 'uploader#new'
  match 'uploader/upload' => 'uploader#upload'
  match 'm' => 'categories#index'
  match 'description' => 'home#description'
  match 'customer' => 'home#customer_resource'
  match 'product' => 'home#product'
  match 'team' => 'home#team'
  match 'contact' => 'home#contact_us'

  root :to => 'home#index'

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/info.rb
# == Schema Information
#
# Table name: infos
#
#  id                :integer          not null, primary key
#  name              :string(255)
#  description       :text
#  address           :string(255)
#  phone             :string(255)
#  qq                :string(255)
#  email             :string(255)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  customer_resource :string(255)
#  team              :string(255)
#

class Info < ActiveRecord::Base
  attr_accessible :address, :description, :email, :name, :phone, :qq, :customer_resource, :team
end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  category   :integer
#  path       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Picture < ActiveRecord::Base
  attr_accessible :category, :name, :path
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include UploaderHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entitye }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    delete_all_picture @category.id

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
  def delete_all_picture category_id
    Picture.find_all_by_category(category_id).each do |p|
      delete_picture p.path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @selected_id = 0
    @pictures = Picture.order('created_at DESC')
    .paginate(page: params[:page], per_page: 12)
  end

  def show
    #@pictures = Picture.find_all_by_category(params[:id])
    @selected_id = 2
    @pictures = Picture.where(category: params[:id]).order('created_at DESC')
    .paginate(page: params[:page], per_page: 12)
    @current_category = Category.find(params[:id])
  end

  def product
    @selected_id = 2
    @pictures = Picture.order('created_at DESC')
    .paginate(page: params[:page], per_page: 12)
    render 'index'
  end

  def description
    @selected_id = 1
  end

  def customer_resource
    @selected_id = 3
  end

  def team
    @selected_id = 4
  end

  def contact_us
    @selected_id = 5
  end

end

app/controllers/info_controller.rb
class InfoController < ApplicationController
	def edit
		@info = Info.first
	end

	def update
		@info = Info.find(params[:id])
		if @info.update_attributes(params[:info])
			redirect_to categories_url
		else
			render action: 'edit'
		end
	end
end

app/controllers/picture_controller.rb
class PictureController < ApplicationController
	def index
		@pictures = Picture.all
	end

	def show
		@picture = Picture.find(params[:id])
	end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
		@picture = Picture.find(params[:id])

		if @picture.update_attributes(params[:picture])
			redirect_to @picture
		else
			render action: "edit"
		end
	end

	def destroy
		@picture = Picture.find(params[:id])
		delete_picture @picture.path
		if @picture.destroy
			redirect_to picture_index_url
		end
	end

end

app/controllers/uploader_controller.rb
class UploaderController < ApplicationController
	def new

	end

	def upload
		uploaded_picture = params[:picture]

		if params[:name].empty?
			name = uploaded_picture.original_filename
		else
			name = params[:name]
		end
		category_id = params[:category][:id]
		dir = picture_store_path uploaded_picture.original_filename, category_id

		File.open(dir, 'wb') do |file|
			file.write(uploaded_picture.read)
    end

    image_optim = ImageOptim.new(:jpegoptim => {max_quality: 20})
    image_optim.optimize_image! dir

		# store in database
		path = picture_show_path uploaded_picture.original_filename, category_id
		picture = Picture.new(category: category_id, name: name, path: path)
		if picture.save
			redirect_to uploader_url
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/helpers/uploader_helper.rb
module UploaderHelper
	def picture_store_path file_name, category_id
		File.join "public", "upload", "#{category_id}_#{file_name}"
	end		

	def picture_show_path file_name, category_id
		File.join "/upload", "#{category_id}_#{file_name}"
	end

	def delete_picture show_path
		absolute_path = "#{Rails.root}/public#{show_path}"
		if File.exist? absolute_path
			File.delete(absolute_path)
		end
	end
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "类别名称" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description, "简介" %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "提交"%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to '详细', @category %> |
<%= link_to '后退', categories_path %>

app/views/categories/index.html.erb
<h1>所有产品类别</h1>

<table>
  <tr>
    <th>名称</th>
    <th>描述</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td><%= link_to '详细', category %></td>
    <td><%= link_to '编辑', edit_category_path(category) %></td>
    <td><%= link_to '删除', category, method: :delete, data: { confirm: '确定要删除吗，会同时删除该类别下的所有图片?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '新增类别', new_category_path %>
<%= link_to '上传照片', 'uploader' %>
<%= link_to '管理照片', picture_index_path %>
<%= link_to '修改公司信息', edit_info_path(Info.first) %>

app/views/categories/new.html.erb
<h1>新建产品目录</h1>

<%= render 'form' %>

<%= link_to '后退', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>名称:</b>
  <%= @category.name %>
</p>

<p>
  <b>描述:</b>
  <%= @category.description %>
</p>


<%= link_to '编辑', edit_category_path(@category) %> |
<%= link_to '后退', categories_path %>

app/views/home/_contact.html.erb
<div class="sidebar_contact">
  <div class="title">联系我们</div>
  <h4>名称</h4>
  <p><%=Info.first.name%></p>
  <h4>地址</h4>
  <p><%=Info.first.address%></p>
  <h4>电话</h4>
  <p><%=Info.first.phone%></p>
  <h4>QQ</h4>
  <p><%=Info.first.qq%></p>
  <h4>邮箱</h4>
  <p><%=Info.first.email%></p>
</div>

app/views/home/_menu.html.erb
<div class="menu">
  <ul>
    <li>
      <a href="/" class="<% if @selected_id == 0 %><%='selected'%><% end %>">首页</a>
    </li>
    <li>
      <a href="/description" class="<% if @selected_id == 1 %><%='selected'%><% end %>">公司简介</a>
    </li>
    <li>
      <a href="/product" class="<% if @selected_id == 2 %><%='selected'%><% end %>">产品展示</a>
    </li>
    <li>
      <a href="/customer" class="<% if @selected_id == 3 %><%='selected'%><% end %>">成功案例</a>
    </li>
    <li>
      <a href="/team" class="<% if @selected_id == 4 %><%='selected'%><% end %>">公司团队</a>
    </li>
    <li>
      <a href="/contact" class="<% if @selected_id == 5 %><%='selected'%><% end %>">联系我们</a>
    </li>
  </ul>
</div>

app/views/home/_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar_content">
    <div class="sidebar_menu_1">
      <a href='/'>首页</a>
    </div>
    <ul>
      <% Category.all.each do |category| %>
          <li>
            <% if category.id.to_s != params[:id] %>
                <%= link_to category.name, action: 'show', id: category.id %>
            <% else %>
                <%= link_to category.name, {action: 'show'}, id: category.id, class: 'selected' %>
            <% end %>
          </li>
      <% end %>
    </ul>
  </div>
  <%= render 'contact'%>
</div>

app/views/home/contact_us.html.erb
<%= render :partial => 'menu', :locals => {:selected_id => @selected_id} %>
<%= render 'sidebar' %>
<div class="home_pic_container">
  <div class="breadcrumb">当前位置 - 联系我们</div>
  <div class="text_content">
    <h4>名称</h4>
    <p><%=Info.first.name%></p>
    <h4>地址</h4>
    <p><%=Info.first.address%></p>
    <h4>电话</h4>
    <p><%=Info.first.phone%></p>
    <h4>QQ</h4>
    <p><%=Info.first.qq%></p>
    <h4>邮箱</h4>
    <p><%=Info.first.email%></p>
  </div>
</div>

app/views/home/customer_resource.html.erb
<%= render :partial => 'menu', :locals => {:selected_id => @selected_id} %>
<%= render 'sidebar' %>
<div class="home_pic_container">
  <div class="breadcrumb">当前位置 - 成功案例</div>
  <div class="text_content">
    <p><%= Info.first.customer_resource %> </p>
  </div>
</div>

app/views/home/description.html.erb
<%= render :partial => 'menu', :locals => {:selected_id => @selected_id}%>
<%= render 'sidebar' %>
<div class="index">
  <div>
    <div class="index_header">
      <h3>公司简介</h3>
    </div>
    <div class="index_content">
      <p><%= Info.first.description %> </p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render :partial => 'menu', :locals => {:selected_id => @selected_id}%>
<%= render 'sidebar' %>
<div class="home_pic_container">
  <div class="breadcrumb">当前位置 - 所有产品</div>
  <%= will_paginate @pictures, previous_label: '« 上一页', next_label: '下一页 »' %>
  <ul>
    <% @pictures.each do |p| %>
        <li class="home_pic">
          <div>
            <a href="<%= p.path %>" title="<%= p.name %>" target="_blank">
              <%= image_tag p.path, class: 'home_img' %>
            </a>
          </div>
        </li>
    <% end %>
    <div class="no_float"></div>
  </ul>
</div>

app/views/home/show.html.erb
<%= render :partial => 'menu', :locals => {:selected => @selected_id} %>
<%= render 'sidebar' %>
<div class="home_pic_container">
  <div class="breadcrumb">当前位置 - <%= @current_category.name %></div>
  <%= will_paginate @pictures, previous_label: '« 上一页', next_label: '下一页 »' %>
  <ul>
    <% @pictures.each do |p| %>
        <li class="home_pic">
          <div>
            <a href="<%= p.path %>" title="<%= p.name %>" target="_blank">
              <%= image_tag p.path, class: 'home_img' %>
            </a>
          </div>
          <div class="pic_name">
            <%= p.name %>
          </div>
        </li>
    <% end %>
    <div class="no_float"></div>
  </ul>
</div>

app/views/home/team.html.erb
<%= render :partial => 'menu', :locals => {:selected_id => @selected_id} %>
<%= render 'sidebar' %>
<div class="home_pic_container">
  <div class="breadcrumb">当前位置 - 公司团队</div>
  <div class="text_content">
    <p><%= Info.first.team %> </p>
  </div>
</div>

app/views/info/edit.html.erb
<%= form_for(@info) do |f| %>
  <div class="field">
    <%= f.label :name, '公司名称' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description, '简介' %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :phone, 'phone'%><br/>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address, '地址' %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email, '邮箱' %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :qq, 'QQ' %><br />
    <%= f.text_field :qq %>
  </div>
    <div class="field">
      <%= f.label :customer_resource, '成功案例' %><br />
      <%= f.text_area :customer_resource %>
    </div>
    <div class="field">
      <%= f.label :team, '公司团队' %><br />
      <%= f.text_area :team %>
    </div>

  <div class="actions">
    <%= f.submit '提交'%>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="header">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= Info.first.name %></title>
	<meta charset="utf-8">
	<link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon">
	<meta name="keyword" content="景隆泽,印务,印刷,奖杯,奖牌,宣传报">
	<meta name="description" content="<%= Info.first.description %>">
  <%= stylesheet_link_tag    'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="main">
	<%= render 'layouts/header' %>
		<%= yield %>
		<div class="no_float"></div>
	</div>
	<div class="no_float"></div>
	<div>
		<!--<%= debug(params) if Rails.env.development? %>-->
	</div>
	<div style="text-align:center;">
		<a href="http://www.miitbeian.gov.cn/">京ICP备14020738号</a>
	</div>
</body>
</html>

app/views/picture/edit.html.erb
<%= form_for @picture do |f| %>
	<div>
		<%= f.label :name, '显示名称'%>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.select :category, options_for_select(Category.all.map{|c| [c.name, c.id]}, selected: @picture.category) %>
	</div>
<% end %>

app/views/picture/index.html.erb
<div>
	<% @pictures.each do |p| %>
		<div class="pic_container">
			<div>
				<%= image_tag p.path, alt: p.name, class: "list_picture"%>
			</div>
			<div>
				类别:<%= Category.find(p.category).name %>
				<%= link_to '修改名称', edit_picture_path(p) %>
				<%= link_to '删除', p, method: :delete, data: { confirm: '确定要删除吗?' } %>
			</div>
		</div>
	<% end %>
</div>

app/views/picture/show.html.erb
<%= image_tag @picture.path, alt: @picture.name %>

app/views/uploader/new.html.erb
<div>
<%= form_tag({action: :upload}, multipart:true) do %>
	<div>
		<%= file_field_tag 'picture' %>
	</div>
	<div>
		<%= label_tag '显示名称(默认与文件名相同)' %>
		<%= text_field_tag 'name' %>
	</div>
	<div>
		<%= collection_select(:category, :id, Category.all, :id, :name) %>
	</div>
	<div>
		<%= submit_tag "上传" %>
	</div>
<% end %>
</div>